language: android
android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra

script: ./gradlew clean build

notifications:
  email:
    recipients:
      - davide.bolognini@gmail.com
    on_success: change
    on_failure: always
